#!/usr/bin/env python3
import locale
locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')

from shutil import copyfile
from md2pdf.core import md2pdf


def compile_resume():
	# Generate web page md file
	copyfile('_resource/resume/hongfei.md', 'resume/hongfei.md')
	with open('resume/hongfei.md', 'a') as resume:
		resume.write('\n')
		resume.write('### Download  \n')
		resume.write('[PDF Version](hongfei.pdf)')
		print("Markdown resume generated")

	# Generate the downloadable pdf file
	md2pdf('resume/hongfei.pdf', md_file_path='_resource/resume/hongfei.md', css_file_path='_resource/markdown/GitHub2.css')
	print("PDF resume generated")

compile_resume()