name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
  workflow_dispatch:
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install bats
        run: npm install -g bats
      - name: Check bats version
        run: bats -v
#  convert-markdown-to-pdf:
#    steps:
#      - uses: valtyr/pandoc-action@v0.1-alpha
  check-env-var-propagates:
    runs-on: ubuntu-latest
    steps:
      - name: Pre-Job environment setup
        run: export ENV1=v1
      - name: Check Env 1
        run: echo $ENV1
      - name: Check Env 2
        run: echo $ENV2
      - name: Middle-Job environment setup
        run: export ENV2=v2
      - name: Check Env 1
        run: echo $ENV1
      - name: Check Env 2
        run: echo $ENV2
